### ISSUE TITLE
关于config配置密码问题

### ISSUE THREAD

**Issue by gatinul** [OrangeXC/mtime#2]
配置文件中如何隐藏数据库密码，注意到此项目中password都为空，请问下如何填充的密码

**Comment by OrangeXC** [comment]
文档只给出 password 可以配置密码，password 为空默认就是没有密码，至于你说的配置文件隐藏数据库密码的需求建议你去：https://github.com/eggjs/egg/issues，毕竟我写的这个项目不涉及到什么隐私。
