### ISSUE TITLE
启动项目报错，mysql的数据从哪里获取？

### ISSUE THREAD

**Issue by Dseekers** [OrangeXC/mtime#42]
你好，初学node希望可以找个项目学习下，现在把项目clone下来启动
期望：
1.npm install
2.npm run dev
3. 可以看到项目

实际：
项目启动报错，我连接了自己本地的mysql,但是发现自己并没mtime这个数据库，这我该如何启动项目

谢谢

**Comment by OrangeXC** [comment]
@Dseekers 手动去数据库里创建一个 mtime

**Comment by Dseekers** [comment]
创建了mtime，但是还是报错一长串的错误

**Comment by OrangeXC** [comment]
@Dseekers  
Windows 下确实有坑，这个需要你慢慢琢磨了，我是在 mac 开发的
